# Generated by Django 4.1.7 on 2023-04-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
