# Generated by Django 4.2 on 2023-04-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
